# Generated by Django 5.2.16 on 2026-08-15 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_guardian_alternate_phone_guardian_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardians', to=settings.AUTH_USER_MODEL),
        ),
    ]
