# Generated by Django 5.0.14 on 2026-07-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_dob_user_gender_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident'), ('guardian', 'Guardian'), ('volunteer', 'Volunteer'), ('security', 'Security')], default='resident', max_length=20),
        ),
    ]
