# Generated by Django 5.0.14 on 2026-07-31 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_is_verified_remove_user_profile_photo_and_more'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='societies.block'),
        ),
        migrations.AddField(
            model_name='user',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='societies.flat'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='securitypersonnel',
            name='assigned_block',
            field=models.CharField(max_length=100),
        ),
    ]
