# Generated by Django 5.2.17 on 2026-08-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_block_user_flat_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='guardian_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('resident', 'Resident'), ('guardian', 'Guardian'), ('society_member', 'Society Member'), ('security', 'Security'), ('volunteer', 'Volunteer')], default='resident', max_length=20),
        ),
    ]
