# Generated by Django 5.2.17 on 2026-08-11 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='active_escalation_level',
            field=models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SECURITY', 'Security Personnel'), ('SOCIETY', 'Society / Admin'), ('VOLUNTEER', 'Volunteer'), ('NONE', 'None')], default='NONE', max_length=30),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='assigned_responder_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='current_stage_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='location_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='description',
            field=models.TextField(blank=True, default='SOS Button Pressed'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='emergency_type',
            field=models.CharField(choices=[('Medical', 'Medical'), ('Fire', 'Fire'), ('Accident', 'Accident'), ('Security', 'Security'), ('General', 'General'), ('Other', 'Other')], default='Medical', max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NOTIFYING_PRIMARY_GUARDIAN', 'Notifying Primary Guardian'), ('NOTIFYING_SECONDARY_GUARDIAN', 'Notifying Secondary Guardian'), ('NOTIFYING_SECURITY', 'Notifying Security'), ('NOTIFYING_SOCIETY', 'Notifying Society'), ('NOTIFYING_VOLUNTEER', 'Notifying Volunteer'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=40),
        ),
        migrations.CreateModel(
            name='EmergencyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emergency.emergencyrequest')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_role', models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SECURITY', 'Security Personnel'), ('SOCIETY', 'Society / Admin'), ('VOLUNTEER', 'Volunteer')], max_length=30)),
                ('escalation_level', models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SECURITY', 'Security Personnel'), ('SOCIETY', 'Society / Admin'), ('VOLUNTEER', 'Volunteer')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('NO_RESPONSE', 'No Response'), ('NOT_SENT', 'Not Sent')], default='PENDING', max_length=20)),
                ('title', models.CharField(default='🚨 SOS ALERT', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('timeout_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='emergency.emergencyrequest')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
