# Generated by Django 5.2.16 on 2026-08-13 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_emergencyrequest_message_and_more'),
        ('societies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_emergencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='societies.society'),
        ),
        migrations.AlterField(
            model_name='emergencynotification',
            name='escalation_level',
            field=models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Member'), ('VOLUNTEER', 'Volunteer'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('SECURITY', 'Security Personnel'), ('SOCIETY', 'Society / Admin'), ('ADMIN', 'Admin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencynotification',
            name='recipient_role',
            field=models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Member'), ('VOLUNTEER', 'Volunteer'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('SECURITY', 'Security Personnel'), ('SOCIETY', 'Society / Admin'), ('ADMIN', 'Admin')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='active_escalation_level',
            field=models.CharField(choices=[('PRIMARY_GUARDIAN', 'Primary Guardian'), ('SECONDARY_GUARDIAN', 'Secondary Guardian'), ('SOCIETY_MEMBER', 'Society Member'), ('VOLUNTEER', 'Volunteer'), ('EMERGENCY_CONTACT', 'Emergency Contact'), ('SECURITY', 'Security Personnel'), ('SOCIETY', 'Society / Admin'), ('ADMIN', 'Admin'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled'), ('NONE', 'None')], default='PRIMARY_GUARDIAN', max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('PENDING', 'Pending'), ('NOTIFYING_PRIMARY_GUARDIAN', 'Notifying Primary Guardian'), ('NOTIFYING_SECONDARY_GUARDIAN', 'Notifying Secondary Guardian'), ('NOTIFYING_SOCIETY_MEMBER', 'Notifying Society Member'), ('NOTIFYING_VOLUNTEER', 'Notifying Volunteer'), ('NOTIFYING_EMERGENCY_CONTACT', 'Notifying Emergency Contact'), ('NOTIFYING_SECURITY', 'Notifying Security'), ('NOTIFYING_SOCIETY', 'Notifying Society'), ('RESPONDING', 'Responding'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=40),
        ),
    ]
