# Generated by Django 5.2.16 on 2026-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0005_emergencyrequest_block_emergencyrequest_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='resolution_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
