# Generated by Django 5.2.17 on 2026-08-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencyrequest_active_escalation_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('PENDING', 'Pending'), ('NOTIFYING_PRIMARY_GUARDIAN', 'Notifying Primary Guardian'), ('NOTIFYING_SECONDARY_GUARDIAN', 'Notifying Secondary Guardian'), ('NOTIFYING_SECURITY', 'Notifying Security'), ('NOTIFYING_SOCIETY', 'Notifying Society'), ('NOTIFYING_VOLUNTEER', 'Notifying Volunteer'), ('IN_PROGRESS', 'In Progress'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=40),
        ),
    ]
