# Generated by Django 5.2.16 on 2026-08-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_emergencyrequest_resolution_notes_and_more'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='societies.block'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencies', to='societies.flat'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='emergency_type',
            field=models.CharField(choices=[('Medical Emergency', 'Medical Emergency'), ('Accident', 'Accident'), ('Fire', 'Fire'), ('Security Threat', 'Security Threat'), ('Crime / Intrusion', 'Crime / Intrusion'), ('Missing Person', 'Missing Person'), ('Women / Child Safety', 'Women / Child Safety'), ('Natural Disaster', 'Natural Disaster'), ('Other', 'Other')], default='Medical Emergency', max_length=50),
        ),
    ]
